# Generated by Django 3.2.8 on 2022-01-10 17:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ادرس ای پی')),
            ],
            options={
                'verbose_name': 'ادرس ای پی',
                'verbose_name_plural': 'ادرس ای پی',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='عنوان اشتراک')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='توضیحات اشتراک')),
                ('price', models.BigIntegerField(default=0, help_text='قیمت براساس ریال می باشد', verbose_name='قیمت اشتراک')),
                ('time', models.IntegerField(default=0, help_text='مدت براساس روز می باشد ', verbose_name='مدت زمان اشتراک')),
                ('discount', models.DecimalField(decimal_places=0, default=0, help_text='(%) تخفیف براساس درصد می باشد ', max_digits=2, verbose_name='تخفیف')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار اشتراک')),
                ('created', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت نمایش اشتراک')),
            ],
            options={
                'verbose_name': 'اشتراک ',
                'verbose_name_plural': ' اشتراک ها ',
            },
        ),
    ]
