# Generated by Django 3.2.8 on 2022-01-10 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting_subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله ')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='آدرس مقاله ')),
                ('descriptions', models.TextField(verbose_name='متن مقاله ')),
                ('thumbnail', models.ImageField(upload_to='image', verbose_name='تصویر مقاله')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='انتشار مقاله ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('p', 'منتشر شده '), ('d', 'پیش نویس'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات ',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کتاب')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='آدرس ')),
                ('descriptions', models.TextField(verbose_name='خلاصه متن کتاب ')),
                ('thumbnail', models.ImageField(upload_to='image_library', verbose_name='عکس کتاب')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(help_text='فقط فایل پی دی اف اپلود شود ', upload_to='pdf')),
                ('is_special', models.BooleanField(default=True, verbose_name='کتاب ویژه')),
                ('status', models.CharField(choices=[('p', 'منتشر شده '), ('d', 'پیش نویس'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'کتابخانه',
                'verbose_name_plural': 'کتابخانه',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='TagLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='برچسب')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_library.library')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها ',
            },
        ),
        migrations.CreateModel(
            name='TagArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='برچسب')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_library.article')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها ',
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نشان داده شود ')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog_library.librarycategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی کتاب خانه ',
                'verbose_name_plural': 'دسته بندی ها کتاب خانه ',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='library',
            name='category',
            field=models.ManyToManyField(related_name='library', to='blog_library.LibraryCategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='library',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='setting_subscription.IPAddress', verbose_name='بازدیدها'),
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نشان داده شود ')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog_library.articlecategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله ',
                'verbose_name_plural': 'دسته بندی ها مقاله ',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='article', to='blog_library.ArticleCategory', verbose_name='دسته بندی '),
        ),
    ]
