# Generated by Django 3.2.8 on 2022-01-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_subscription', '0001_initial'),
        ('blog_library', '0002_remove_library_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting_subscription.ipaddress')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_library.library')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='blog_library.LibraryHits', to='setting_subscription.IPAddress', verbose_name='بازدیدها'),
        ),
    ]
