# Generated by Django 3.2.8 on 2021-12-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0004_auto_20211228_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name': 'امتیاز کاربر', 'verbose_name_plural': 'امتیاز کاربران'},
        ),
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='امتیاز'),
        ),
    ]
