# Generated by Django 3.2.8 on 2022-01-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0005_auto_20211229_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'رتبه بندی', 'verbose_name_plural': 'رتبه بندی های'},
        ),
    ]
